# Generated by Django 3.1.7 on 2021-02-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='profile_qr/'),
        ),
    ]
