# Generated by Django 3.1.7 on 2021-02-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
